# Generated by Django 4.0.4 on 2022-08-01 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='list_who_like_photo',
            field=models.ManyToManyField(blank=True, related_name='account_liked_photo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_owner_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
