# Generated by Django 4.0.4 on 2022-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_petphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='tagged_pets',
        ),
    ]
