# Generated by Django 4.0.4 on 2022-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_petphoto_tagged_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='tagged_pets',
            field=models.ManyToManyField(to='main_app.pet'),
        ),
    ]
