# Generated by Django 4.0.4 on 2022-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_petphoto_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Day of birth'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Pet name'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Pet image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('femail', 'femail'), ('Do not show', 'Do not show')], default='Do not show', max_length=30, null=True),
        ),
    ]
